#Makefile 
CC=gcc
CXX=g++
CFLAGS=-I. -lpthread -Wall -std=c++11  -pthread
# SRCS: polym_device.cpp Queue.cpp
# 	$(CXX) $(CFLAGS)  -o main polym_device.cpp Queue.cpp

SRCS: polym_device.cpp 
	$(CXX) $(CFLAGS)  -o main polym_device.cpp 

# SRCS: binary_converter.cpp 
# 	$(CXX) $(CFLAGS)  -o main binary_converter.cpp


.PHONY: clean
