#Makefile 
CC=gcc
CXX=g++
CFLAGS=-I. -lpthread -Wall -std=c++11  -pthread
# SRCS: threadpool_func.cpp Queue.cpp
# 	$(CXX) $(CFLAGS)  -o main threadpool_func.cpp Queue.cpp

SRCS: threadpool_func.cpp 
	$(CXX) $(CFLAGS)  -o main threadpool_func.cpp 


.PHONY: clean
