#Makefile 
CC=gcc
CXX=g++
CFLAGS=-I. -lpthread -Wall -std=c++11  -pthread
# SRCS: func_pointer_semaphore.cpp Queue.cpp
# 	$(CXX) $(CFLAGS)  -o main func_pointer_semaphore.cpp Queue.cpp

SRCS: func_pointer_semaphore.cpp 
	$(CXX) $(CFLAGS)  -o main func_pointer_semaphore.cpp 


.PHONY: clean
