#Makefile 
CC=gcc
CXX=g++
CFLAGS=-I. -Wall -std=c++11
SOURCE= main.cpp Device.cpp Test_Device.cpp
SRCS: main.cpp \
    Device.cpp \
    Test_Device.cpp
	$(CXX) $(CFLAGS)  -o program $(SOURCE) 

.PHONY: clean
