#Makefile 
CC=gcc
CXX=g++
CFLAGS=-I. -lpthread -Wall -std=c++11  -pthread
# SRCS: tp_semaphore.cpp
# 	$(CXX) $(CFLAGS)  -o main tp_semaphore.cpp

SRCS: binary_converter.cpp 
	$(CXX) $(CFLAGS)  -o main binary_converter.cpp


.PHONY: clean
