#Makefile 
CC=gcc
CXX=g++
CFLAGS=-I. -lpthread -Wall -std=c++11  -pthread
# SRCS: semaphore_class.cpp
# 	$(CXX) $(CFLAGS)  -o main semaphore_class.cpp

SRCS: semaphore_class.cpp 
	$(CXX) $(CFLAGS)  -o main semaphore_class.cpp


.PHONY: clean
